<a href="https://colab.research.google.com/github/LIBY70/Data-Analysis/blob/main/ida_week3_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab3: 데이터 분석에 필요한 주요 라이브러리

본 실습 자료는 『배워서 바로 써먹는 데이터 분석with 파이썬』(설진욱, 생능북스)를 참고하여 제작되었습니다.

## 1. numpy

numpy란? 주로 데이터 처리와 수치 계산에 사용되는 라이브러리

**주요 기능**
- 고성능 수치 계산과 수치 해석
- 통계, 선형대수, 행렬 계산
- 벡터, 다차원 배열 계산
- 난수 생성, 푸리에 변환 기능 지원

숫자계산

In [ ]:
import numpy as np

**배열 생성**

In [ ]:
# nd(n차원)array 배열 생성
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
# 0으로 채워진 배열 생성: np.zeros()
np.zeros((3, 3))  # 0으로 채워진 3x3 배열 생성

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 1로 채워진 배열 생성: np.ones()
np.ones((2, 4))  # 1로 채워진 2x4 배열 생성

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# 범위 지정하여 배열 생성: np.arange()
np.arange(10)   # 0부터 10-1까지

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 범위 지정하여 배열 생성: np.arange()
np.arange(0, 10, 2)  # 0부터 10-1까지 2씩 증가하는 배열

array([0, 2, 4, 6, 8])

In [ ]:
# 랜덤 배열 생성: np.random.rand()
np.random.rand(3, 3)  # 3x3 랜덤 배열 생성

array([[0.89850483, 0.39313308, 0.86265962],
       [0.79040761, 0.95280496, 0.20609246],
       [0.38047906, 0.50220002, 0.27111915]])

**배열 조작**

In [ ]:
# 형상 변경: np.reshape()
arr1 = np.arange(6)

np.reshape(arr1, [2, 3])

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 전치(행과 열을 바꿈): np.transpose()
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

np.transpose(arr1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# 배열 병합: np.concatenate()
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 3, 5], [7, 9, 11]])

np.concatenate([arr1, arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  3,  5],
       [ 7,  9, 11]])

In [ ]:
# np.concatenate() 축 지정
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 3, 5], [7, 9, 11]])

np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  1,  3,  5],
       [ 4,  5,  6,  7,  9, 11]])

**배열 연산**

In [ ]:
# numpy 배열 기본연산: 배열 사칙연산
a_arr = np.array([1, 2, 3])
b_arr = np.array([4, 5, 6])
np.add(a_arr, b_arr)

array([5, 7, 9])

In [ ]:
a_arr + b_arr

array([5, 7, 9])

In [ ]:
# numpy 배열 기본연산: np.sum()함수사용
data1 = np.array([10, 20, 30, 40, 50])
np.sum(data1)

np.int64(150)

In [ ]:
# 행렬 곱 (dot product): np.dot()함수 사용
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

np.dot(arr1, arr2)

array([[19, 22],
       [43, 50]])

In [ ]:
# 브로드캐스팅 (차원 자동 확장)
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # 2x3
arr2 = np.array([1, 2, 3])  # 1x3

arr1 + arr2  # B가 A의 행 크기에 맞게 자동 확장

array([[2, 4, 6],
       [5, 7, 9]])

**유니버설 (universal) 함수**

데이터의 원소별로 연산을 수행

In [ ]:
# 절댓값: np.abs()
arr = np.array([1, -1, 2, -3])
np.abs(arr)

array([1, 1, 2, 3])

In [ ]:
# 제곱: np.square()
arr = np.arange(4)
np.square(arr)

array([0, 1, 4, 9])

In [ ]:
# 제곱근: np.sqrt()
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [ ]:
# 자연상수 e의 제곱: np.exp()
np.exp(arr)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [ ]:
# 로그: np.log()
arr = np.array([1, 2, 3, 4])
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
arr = np.array([1, 10, 100, 1000])
np.log10(arr)

array([0., 1., 2., 3.])

In [ ]:
arr = np.array([1, 2, 4, 8, 16, 32])
np.log2(arr)

array([0., 1., 2., 3., 4., 5.])

In [ ]:
# inf: infinite / NaN: Not a Number
arr1 = np.array([0, 1, 10, 100])
arr2 = np.log10(arr1)
arr2

/tmp/ipykernel_13261/2393287195.py:3: RuntimeWarning: divide by zero encountered in log10
  arr2 = np.log10(arr1)

array([-inf,   0.,   1.,   2.])

In [ ]:
arr3 = np.log10(arr2)
arr3

/tmp/ipykernel_13261/3634474159.py:1: RuntimeWarning: divide by zero encountered in log10
  arr3 = np.log10(arr2)
/tmp/ipykernel_13261/3634474159.py:1: RuntimeWarning: invalid value encountered in log10
  arr3 = np.log10(arr2)

array([    nan,    -inf, 0.     , 0.30103])

In [ ]:
# 유효한 값인지 확인: np.isnan() nan=True, 아니면 False
np.isnan(arr3)

array([ True, False, False, False])

In [ ]:
# inf가 포함됐는지 확인: np.isinf() inf면 True
np.isinf(arr2)

array([ True, False, False, False])

In [ ]:
# inf의 반대: np.isfinite() inf = False
np.isfinite(arr2)

array([False,  True,  True,  True])

**기술 통계**

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 합계: np.sum()
np.sum(arr)

np.int64(45)

In [ ]:
# 평균: np.mean(), 표준편차: np.std(), 분산: np.var()
np.mean(arr), np.std(arr), np.var(arr)

(np.float64(4.5), np.float64(2.8722813232690143), np.float64(8.25))

In [ ]:
# 최댓값: np.max(), 최솟값: np.min(), 중앙값: np.median()
np.max(arr), np.min(arr), np.median(arr)

(np.int64(9), np.int64(0), np.float64(4.5))

**(참고: 인스턴스의 method)**

In [ ]:
arr.sum(), arr.mean(), arr.std(), arr.var() #얘는 왜 열로 출력?

(np.int64(45),
 np.float64(4.5),
 np.float64(2.8722813232690143),
 np.float64(8.25))

In [ ]:
arr.max(), arr.min(), #arr.median()

(np.int64(9), np.int64(0))

## 2. pandas

pandas란? 표 형식의 데이터를 다루는 데 특화된 데이터 분석 라이브러리

**주요 기능**

- 누락 데이터(NaN) 처리의 유연한 기능
- 가변적인 사이즈 조절 기능(데이터프레임을 사용한 고차원적인 열을 추가 · 삭제)
- 데이터의 집계 및 변환 기능
- 자동적이며 명확한 데이터 정렬 기능
- 다양한 형식의 데이터 입출력 기능
- 축(axes)의 다중 라벨링(labeling)
- 시계열 데이터 처리 기능
- 레이블 기반의 슬라이싱, 인덱싱, 부분 추출 기능
- 데이터셋에 대한 피보팅과 유연한 형상 변경 기능

**pandas에 적합한 데이터 유형**

- 통계 데이터셋
- 시계열 형식의 데이터
- 데이터베이스 테이블이나 스프레드시트와 같이 여러 유형의 열(column)로 구성된 표 형식의 데이터

**numpy와 pandas 비교**

| 구분 | numpy | pandas |
| :--- | :--- | :--- |
| **핵심 객체** | `ndarray` (N-차원 배열) | `Series`, `DataFrame` (표 형태) |
| **데이터 타입** | 주로 동일한 타입의 수치 데이터 | 서로 다른 타입의 데이터 혼합 가능 (열별) |
| **주요 용도** | 수치 계산, 선형 대수, 행렬 연산 | 데이터 전처리, 통계 분석, 입출력(CSV, Excel) |
| **특징** | 수학적 연산 속도가 매우 빠름 | 색인(Index)와 라벨을 통한 데이터 관리 용이 |

### Series

축 방향으로 label을 갖는 1차원 배열로, 동일한 자료구조를 저장

In [ ]:
from pandas import Series #판다스라는 라이브러리에서 시리즈를 바로 사용하겠다.

mylist = [10, 40, 30]
myindex = ['김유신', '이순신', '강감찬']

Series(mylist)

0    10
1    40
2    30
dtype: int64

In [ ]:
Series(data=mylist)

0    10
1    40
2    30
dtype: int64

In [ ]:
Series(data=mylist, index=myindex)

김유신    10
이순신    40
강감찬    30
dtype: int64

In [ ]:
Series(data=mylist, index=myindex, dtype=float)

김유신    10.0
이순신    40.0
강감찬    30.0
dtype: float64

In [ ]:
myseries = Series(data=mylist, index=myindex)
myseries.index

Index(['김유신', '이순신', '강감찬'], dtype='object')

In [ ]:
myseries.values

array([10, 40, 30])

In [ ]:
myseries.name = "점수"
myseries.index.name = "이름"

In [ ]:
myseries

이름
김유신    10
이순신    40
강감찬    30
Name: 점수, dtype: int64

**Series의 데이터 읽기와 쓰기**

In [ ]:
from pandas import Series

myindex = ['용산구', '마포구', '영등포구', '서대문구', '광진구', '은평구', '서초구']
mylist = [50, 60, 40, 80, 70, 30, 20]
myseries = Series(data=mylist, index=myindex)
myseries

용산구     50
마포구     60
영등포구    40
서대문구    80
광진구     70
은평구     30
서초구     20
dtype: int64

In [ ]:
# '서대문구' 색인 조회
myseries[['서대문구']]

서대문구    80
dtype: int64

In [ ]:
# 검색 시 콜론을 사용하면 연속적인 데이터 검색 가능
myseries['서대문구':'은평구']

서대문구    80
광진구     70
은평구     30
dtype: int64

![](https://github.com/user-attachments/assets/7eb291a9-bf15-4dbb-9711-f21bf6242db7)

In [ ]:
# 서로 떨어져 있는 이산형 데이터(discrete data)는 콤마를 사용해 검색
myseries[['서대문구', '서초구']]

서대문구    80
서초구     20
dtype: int64

![](https://github.com/user-attachments/assets/9e92786a-bc9f-441b-966a-e421a433b658)

In [ ]:
# 데이터 변경
myseries[['은평구']] = 40

In [ ]:
myseries[['용산구' , '서대문구']] = 55
myseries

용산구     55
마포구     60
영등포구    40
서대문구    55
광진구     70
은평구     40
서초구     20
dtype: int64

**Series간 산술 연산**

In [ ]:
from pandas import Series

myindex1 = ['강호민', '유재준', '김제명', '신동진']
mylist1 = [30, 40, 50, 60]

myindex2 = ['강호민', '유재준', '김제명', '이수진']
mylist2 = [20, 40, 60, 70]

myseries1 = Series(data=mylist1, index=myindex1)
myseries2 = Series(data=mylist2, index=myindex2)

In [ ]:
# 산술 연산 시 데이터가 한쪽에 데이터가 존재하지 않으면 그 결과는 NaN
myseries1 + myseries2

강호민     50.0
김제명    110.0
신동진      NaN
유재준     80.0
이수진      NaN
dtype: float64

![](https://github.com/user-attachments/assets/74cfb5aa-de99-4628-a3ac-e02767f6c73f)

In [ ]:
# fill_value를 사용해 빈 값 처리
myseries1.add(myseries2, fill_value = 0)

강호민     50.0
김제명    110.0
신동진     60.0
유재준     80.0
이수진     70.0
dtype: float64

In [ ]:
# add, sub, mul, div 가능
myseries1.sub(myseries2, fill_value = 0)

강호민    10.0
김제명   -10.0
신동진    60.0
유재준     0.0
이수진   -70.0
dtype: float64

**중복 값이 있는 경우**

In [ ]:
mylist = ['라일락', '코스모스', '코스모스','백일홍', '코스모스', '코스모스', '들장미', '들장미', '라일락', '라일락']
myseries = Series(mylist)
myseries

0     라일락
1    코스모스
2    코스모스
3     백일홍
4    코스모스
5    코스모스
6     들장미
7     들장미
8     라일락
9     라일락
dtype: object

In [ ]:
# unique(): 중복 값 제외
myseries.unique()

array(['라일락', '코스모스', '백일홍', '들장미'], dtype=object)

![](https://github.com/user-attachments/assets/739f0558-96f6-4f3e-9a3f-b9e93015de20)

In [ ]:
# value_counts(): 항목 별 빈도 수
myseries.value_counts()

코스모스    4
라일락     3
들장미     2
백일홍     1
Name: count, dtype: int64

![](https://github.com/user-attachments/assets/c5c09417-6b10-4b33-8f80-fc636729589c)

In [ ]:
# isin(): 값이 ()안 리스트에 있는지 학인 boolean
myseries.isin(['들장미', '라일락'])

0     True
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool

![](https://github.com/user-attachments/assets/6e70ab16-92f2-4975-9855-f0d2d9ac3415)

### DataFrame

표 형태의 2차원 데이터로 여러 유형의 데이터를 담을 수 있음

In [2]:
import numpy as np
from pandas import DataFrame

mydata=np.arange(9).reshape((3, 3))
myframe = DataFrame(
    data=mydata,
    index=['용산구', '마포구', '은평구'],
    columns=['김철수', '이영희', '정준수']
)

myframe

     김철수  이영희  정준수
용산구    0    1    2
마포구    3    4    5
은평구    6    7    8

In [3]:
sdata = {'지역' : ['용산구', '마포구'], '연도' : [2019, 2020]}
DataFrame(data=sdata)

    지역    연도
0  용산구  2019
1  마포구  2020

In [4]:
# 중첩 dictionary
sdata = {'용산구' : {2020: 10, 2021: 20}, '마포구' : {2020: 30, 2021: 40, 2022: 50}}
DataFrame(sdata)

       용산구  마포구
2020  10.0   30
2021  20.0   40
2022   NaN   50

In [12]:
# 길이가 같은 list를 각 column으로, 리스트라면 array의 길이가 같함.
sdata = {
            '도시' : ['서울', '서울', '서울', '부산', '부산'],
            '연도' : [2000, 2001, 2002, 2001, 2002],
            '실적' : [150, 170, 360, 240, 290]
        }
DataFrame(sdata)

   도시    연도   실적
0  서울  2000  150
1  서울  2001  170
2  서울  2002  360
3  부산  2001  240
4  부산  2002  290

In [10]:
# 색인 지정
myframe = DataFrame(sdata, index=['one', 'two', 'three', 'four', 'five'])

In [11]:
myframe.columns

Index(['도시', '연도', '실적'], dtype='object')

In [13]:
myframe.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [14]:
myframe.columns.name, myframe.index.name

(None, None)

In [15]:
myframe.columns.name = "컬럼1"
myframe.index.name = "색인1"
myframe

컬럼1    도시    연도   실적
색인1
one    서울  2000  150
two    서울  2001  170
three  서울  2002  360
four   부산  2001  240
five   부산  2002  290

In [16]:
myframe.columns

Index(['도시', '연도', '실적'], dtype='object', name='컬럼1')

In [17]:
myframe.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object', name='색인1')

In [18]:
# DataFrame 내용 확인
myframe.values

array([['서울', 2000, 150],
       ['서울', 2001, 170],
       ['서울', 2002, 360],
       ['부산', 2001, 240],
       ['부산', 2002, 290]], dtype=object)

In [19]:
# 자료형 확인
myframe.dtypes

컬럼1
도시    object
연도     int64
실적     int64
dtype: object

In [20]:
# transpose
myframe.T

색인1   one   two three  four  five
컬럼1
도시     서울    서울    서울    부산    부산
연도   2000  2001  2002  2001  2002
실적    150   170   360   240   290

**DataFrame 데이터 읽기와 쓰기**

In [21]:
import numpy as np
from pandas import DataFrame

myindex = ['이순신', '김유신', '강감찬', '광해군', '연산군']
mycolumns = ['서울', '부산', '광주', '목포', '경주']

myframe = DataFrame(np.reshape([10 * i for i in range(1, 26)], (5, 5)),
                     index=myindex,
                     columns = mycolumns)
myframe

      서울   부산   광주   목포   경주
이순신   10   20   30   40   50
김유신   60   70   80   90  100
강감찬  110  120  130  140  150
광해군  160  170  180  190  200
연산군  210  220  230  240  250

![](https://github.com/user-attachments/assets/fda916b6-39c2-4c16-9329-3e90ab07478c)

**행 데이터 추출: iloc index locate , loc loc = locate**

In [41]:
# 1행
myframe.iloc[1] # serise

서울     60
부산     70
광주     80
목포     90
경주    100
Name: 김유신, dtype: int64

In [23]:
# 1, 3행
myframe.iloc[[1,3]] #dataframe

      서울   부산   광주   목포   경주
김유신   60   70   80   90  100
광해군  160  170  180  190  200

In [27]:
# 0~3행
myframe.iloc[:3]

      서울   부산   광주   목포   경주
이순신   10   20   30   40   50
김유신   60   70   80   90  100
강감찬  110  120  130  140  150

In [30]:
# 2씩 건너뛰기
myframe.iloc[0::2]

      서울   부산   광주   목포   경주
이순신   10   20   30   40   50
강감찬  110  120  130  140  150
연산군  210  220  230  240  250

In [42]:
# '이순신' 행만 추출 (Series)
result = myframe.loc['이순신']
result

서울    10
부산    20
광주    30
목포    40
경주    50
Name: 이순신, dtype: int64

In [33]:
# 자료형: Series
type(result)

pandas.core.series.Series

![](https://github.com/user-attachments/assets/8a2ca5af-1413-440f-abc7-e634a8932f62)

In [40]:
# '이순신' 행만 추출 (DataFrame) 값을 가져오겠다
result = myframe.loc[['이순신']]
result

     서울  부산  광주  목포  경주
이순신  10  20  30  40  50

In [ ]:
# 자료형: DataFrame
type(result)

![](https://github.com/user-attachments/assets/4cc5cda8-4893-4308-8eb2-947965dfd031)

In [38]:
# '이순신', '강감찬' 행만 추출 (DataFrame)
result = myframe.loc[['이순신', '강감찬']]
result

      서울   부산   광주   목포   경주
이순신   10   20   30   40   50
강감찬  110  120  130  140  150

**열 데이터 포함 추출**

In [43]:
# '강감찬' 행의 '광주' 열
myframe.loc[['강감찬'], ['광주']]

      광주
강감찬  130

In [44]:
myframe.loc[['연산군', '강감찬'], ['광주', '목포']]

      광주   목포
연산군  230  240
강감찬  130  140

![](https://github.com/user-attachments/assets/680da84f-c881-4877-b3ad-5457fd20769a)

In [47]:
myframe.loc['김유신':'광해군', '광주':'목포'] #왜 광해군 포함돼서 츨력? 문자열일땐 포함해서 출력

      광주   목포
김유신   80   90
강감찬  130  140
광해군  180  190

![](https://github.com/user-attachments/assets/68311e7e-b122-4bd6-8488-a2e4941799ca)

In [48]:
# bool 처리
myframe.loc[[False, True, True, False, True]]

      서울   부산   광주   목포   경주
김유신   60   70   80   90  100
강감찬  110  120  130  140  150
연산군  210  220  230  240  250

![](https://github.com/user-attachments/assets/45fa3a8f-213b-4042-85ff-50ec3710be0b)

In [49]:
# '부산' 값이 100 이하
myframe.loc[myframe['부산'] <= 100]

     서울  부산  광주  목포   경주
이순신  10  20  30  40   50
김유신  60  70  80  90  100

![](https://github.com/user-attachments/assets/354120d6-3c92-4089-8e6b-f58f93b9c395)

In [50]:
# '목포' 값이 140과 일치
myframe.loc[myframe['목포'] == 140]

      서울   부산   광주   목포   경주
강감찬  110  120  130  140  150

![](https://github.com/user-attachments/assets/1a8e5e93-f7e4-42a0-a9d4-a428081eb672)

**복합 조건**

예) '부산' 값이 70 이상이고 '목포' 값이 140 이상

In [53]:
myframe.loc[myframe['부산'] >= 70 and myframe['목포'] >= 140]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [54]:
cond1 = myframe['부산'] >= 70
cond2 = myframe['목포'] >= 140
type(cond1)

pandas.core.series.Series

In [62]:
df = DataFrame([cond1, cond2])
df

      이순신    김유신   강감찬   광해군   연산군
부산  False   True  True  True  True
목포  False  False  True  True  True

In [63]:
myframe.loc[df.all()] # all = and 연산

      서울   부산   광주   목포   경주
강감찬  110  120  130  140  150
광해군  160  170  180  190  200
연산군  210  220  230  240  250

![](https://github.com/user-attachments/assets/2b78bd3c-2c67-4605-a7a3-a6f1e3ebf344)

any -> all 오타

In [64]:
myframe.loc[df.any()]

      서울   부산   광주   목포   경주
김유신   60   70   80   90  100
강감찬  110  120  130  140  150
광해군  160  170  180  190  200
연산군  210  220  230  240  250

![](https://github.com/user-attachments/assets/45f04b12-6206-41b3-a286-ca41db57483b)

In [65]:
# 값의 변경
myframe.loc[['이순신', '강감찬'], ['부산']] = 30
myframe

      서울   부산   광주   목포   경주
이순신   10   30   30   40   50
김유신   60   70   80   90  100
강감찬  110   30  130  140  150
광해군  160  170  180  190  200
연산군  210  220  230  240  250

In [66]:
myframe.loc['김유신':'광해군', ['경주']] = 80
myframe

      서울   부산   광주   목포   경주
이순신   10   30   30   40   50
김유신   60   70   80   90   80
강감찬  110   30  130  140   80
광해군  160  170  180  190   80
연산군  210  220  230  240  250

In [67]:
# '연산군'의 모든 값(:)을 50으로 변경
myframe.loc[['연산군'], :] = 50
myframe

      서울   부산   광주   목포  경주
이순신   10   30   30   40  50
김유신   60   70   80   90  80
강감찬  110   30  130  140  80
광해군  160  170  180  190  80
연산군   50   50   50   50  50

In [68]:
# 모든 사람의 '광주' 값을 60으로 변경
myframe.loc[:, ['광주']] = 60
myframe

      서울   부산  광주   목포  경주
이순신   10   30  60   40  50
김유신   60   70  60   90  80
강감찬  110   30  60  140  80
광해군  160  170  60  190  80
연산군   50   50  60   50  50

In [69]:
# TODO: '경주' 값이 60 이하인 사람들의 '경주'와 '광주' 값을 모두 0으로 변경

**DataFrame의 산술 연산**

In [76]:
import numpy as np
from pandas import Series, DataFrame

myindex = ['강호민', '유재준', '신동진'] #색인
mylist = [30, 40, 50]

myseries = Series(data=mylist, index=myindex)
myseries

강호민    30
유재준    40
신동진    50
dtype: int64

In [77]:
myindex2 = ['강호민', '유재준', '이수진']
mycolumns = ['서울', '부산', '경주']

myframe = DataFrame(np.reshape([10 * i for i in range(1, 10)], (3, 3)),
                     index=myindex2,
                     columns = mycolumns)
myframe

     서울  부산  경주
강호민  10  20  30
유재준  40  50  60
이수진  70  80  90

In [72]:
# DataFrame과 Series의 산술 연산 가능
# axis = 0: Series의 색인과 DataFrame의 색인 간 연산
myframe.add(myseries, axis=0)

       서울    부산     경주
강호민  40.0  50.0   60.0
신동진   NaN   NaN    NaN
유재준  80.0  90.0  100.0
이수진   NaN   NaN    NaN

![](https://github.com/user-attachments/assets/ffc6d369-b12a-4621-95cf-b6f241c0bad6)

In [75]:
myindex3 = ['강호민', '유재준', '김병준']
mycolumns2 = ['서울', '부산', '대구']

myframe2 = DataFrame(np.reshape([5 * i for i in range(1, 10)], (3, 3)),
                     index=myindex3, # 색인을 맞춰 연산해라
                     columns = mycolumns2)
myframe2

     서울  부산  대구
강호민   5  10  15
유재준  20  25  30
김병준  35  40  45

In [78]:
myframe

     서울  부산  경주
강호민  10  20  30
유재준  40  50  60
이수진  70  80  90

In [80]:
myframe.add(myframe2, fill_value=0) # 다시이해

       경주    대구    부산    서울
강호민  30.0  15.0  30.0  15.0
김병준   NaN  45.0  40.0  35.0
유재준  60.0  30.0  75.0  60.0
이수진  90.0   NaN  80.0  70.0

![](https://github.com/user-attachments/assets/c0f5bb0f-de56-47b7-bffc-d92a1a864364)

**파일 입출력**

`.csv` (Comma-Separated Values) 파일: `read_csv()`, `to_csv()`

In [90]:
import pandas as pd

filename = 'memberInfo.csv'
df = pd.read_csv(filename)
df

    id  kor  eng
0  김철수   60   70
1  홍길동   70   75
2  박영희   80   80

In [93]:
# 특정 column을 색인으로 지정
df.set_index(keys=['id'])

     kor  eng
id
김철수   60   70
홍길동   70   75
박영희   80   80

In [84]:
# 기존 column 유지: drop=False
df.set_index(keys=['id'], drop=False)

      id  kor  eng
id
김철수  김철수   60   70
홍길동  홍길동   70   75
박영희  박영희   80   80

In [85]:
# 파일을 읽을 때 특정 column을 색인으로
filename = 'memberInfo.csv'
df2 = pd.read_csv(filename, index_col='id')
df2

     kor  eng
id
김철수   60   70
홍길동   70   75
박영희   80   80

In [87]:
myframe.to_csv("out.csv")
myframe.to_csv("out_no_index.csv", index=False)
myframe.to_csv("out_no_header.csv", header=False)
myframe.to_csv("out_no_index_no_header.csv", index=False, header=False)

In [88]:
# 참고: 엑셀 파일(.xlsx, .xls) 읽고 쓰기: read_excel(), to_excel()
myframe.to_excel("out.xlsx")